name: Java CI with Maven

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: my-vm

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
      - name: docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Docker Build and Push
        run: |
          docker build -t weebad/demo-petclinic:${{ github.run_number }} .
          docker push weebad/demo-petclinic:${{ github.run_number }}
          
        
